### ISSUE TITLE
Fix Example

### ISSUE THREAD

**Issue by deadraid** [matthewhartstonge/argon2#1]
// NOTE The following can be shortened by writing for instance:
//
//   ok, err := cfg.VerifyEncoded(password, encoded)
//
replace

ok, err := argon2.VerifyEncoded(password, encoded)
 
The method VerifyEncoded is not related to the Config structure.
Thank you for your library!

**Comment by matthewhartstonge** [comment]
Good spotting! 
Sorry about that!
